export const dataMap = {
  key: ["Menu Map", "hover panel text"],
  "h3-index": [["N/A"], ["H3 Index", ""]],
  row_col: [["N/A"], ["Row/Col", ""]],
  female_educational_attainment_mean: [["Demographics", "Female Education", "N/A"], ["Avg. Female Education", "years"]],
  females_0_4: [["Population", "Female 0-4", "N/A"], ["Population", "females"]],
  females_0_9: [["Population", "Female 0-9", "N/A"], ["Population", "females"]],
  females_10_14: [["Population", "Female 10-14", "N/A"], ["Population", "females"]],
  females_15_49: [["Population", "Female 15-49", "N/A"], ["Population", "females"]],
  females_50_64: [["Population", "Female 50-64", "N/A"], ["Population", "females"]],
  females_5_9: [["Population", "Female 5-9", "N/A"], ["Population", "females"]],
  females_65_plus: [["Population", "Females 65+", "N/A"], ["Population", "females"]],
  male_educational_attainment_mean: [["Demographics", "Male Education", "N/A"], ["Avg. Male Education", "years"]],
  males_0_4: [["Population", "Male 0-4", "N/A"], ["Population", "males"]],
  males_0_9: [["Population", "Male 0-9", "N/A"], ["Population", "males"]],
  males_10_14: [["Population", "Male 10-14", "N/A"], ["Population", "males"]],
  males_15_49: [["Population", "Male 15-49", "N/A"], ["Population", "males"]],
  males_50_64: [["Population", "Male 50-64", "N/A"], ["Population", "males"]],
  males_5_9: [["Population", "Male 5-9", "N/A"], ["Population", "males"]],
  males_65_plus: [["Population", "Males 65+", "N/A"], ["Population", "males"]],
  pop_0_4: [["Population", "Children 0-4", "N/A"], ["Population", "people"]],
  pop_0_9: [["Population", "Children 0-9", "N/A"], ["Population", "people"]],
  pop_10_14: [["Population", "Youth 10-14", "N/A"], ["Population", "people"]],
  pop_15_49: [["Population", "People 15-49", "N/A"], ["Population", "people"]],
  pop_50_64: [["Population", "People 50-64", "N/A"], ["Population", "people"]],
  pop_5_9: [["Population", "Children 5-9", "N/A"], ["Population", "people"]],
  pop_65_plus: [["Population", "People 65+", "N/A"], ["Population", "people"]],
  population: [["Population", "All", "N/A"], ["Population", "people"]],
  pregnancies: [["Demographics", "Pregnancies", "N/A"], ["Pregnancies", ""]],
  births: [["Demographics", "Births", "N/A"], ["Births", ""]],
  rwi: [["Demographics", "Relative Wealth Index", "N/A"], ["Relative Wealth Index", ""]],
  underweight: [["Demographics", "Underweight", "N/A"], ["Underweight", ""]],
  time_delta_constructed_sites_all_education_facilities_fixed: [["Impact", "Current Impact", "School"], ],
  time_delta_constructed_sites_all_health_facilities_optimal: [["Impact", "Current Impact", "Healthcare"], ],
  time_delta_constructed_sites_health_centers_optimal: [["Impact", "Current Impact", "Health Center"], ],
  time_delta_constructed_sites_health_posts_optimal: [["Impact", "Current Impact", "Health Post"], ],
  time_delta_constructed_sites_major_hospitals_optimal: [["Impact", "Current Impact", "Major Hospital"], ],
  time_delta_constructed_sites_primary_schools_fixed: [["Impact", "Current Impact", "Primary School"], ],
  time_delta_constructed_sites_secondary_schools_fixed: [["Impact", "Current Impact", "Secondary School"], ],
  time_delta_constructed_sites_semi_dense_urban_optimal: [["Impact", "Current Impact", "Semi Dense Urban"], ],
  //   this needs work
  time_delta_no_sites_all_education_facilities_fixed: [["Impact", "Potential Impact", "School"], ],
  time_delta_no_sites_all_health_facilities_optimal: [["Impact", "Potential Impact", "Healthcare"], ],
  time_delta_no_sites_health_centers_optimal: [["Impact", "Potential Impact", "Health Center"], ],
  time_delta_no_sites_health_posts_optimal: [["Impact", "Potential Impact", "Health Post"], ],
  time_delta_no_sites_major_hospitals_optimal: [["Impact", "Potential Impact", "Major Hospital"], ],
  time_delta_no_sites_primary_schools_fixed: [["Impact", "Potential Impact", "Primary School"], ],
  time_delta_no_sites_secondary_schools_fixed: [["Impact", "Potential Impact", "Secondary School"], ],
  time_delta_no_sites_semi_dense_urban_optimal: [["Impact", "Potential Impact", "Market"], ],
  //   this needs work
  travel_time_all_education_facilities_fixed: [["Travel Time", "With All Bridges", "To School"], ],
  travel_time_all_health_facilities_optimal: [["Travel Time", "With All Bridges", "To Healthcare"], ],
  travel_time_constructed_sites_all_education_facilities_fixed: [["Travel Time", " With Constructed Bridges", "To School"], ],
  travel_time_constructed_sites_all_health_facilities_optimal: [["Travel Time", "With Constructed Bridges", "To Healthcare"], ],
  travel_time_constructed_sites_health_centers_optimal: [["Travel Time", "With Constructed Bridges", "To Health Center"], ],
  travel_time_constructed_sites_health_posts_optimal: [["Travel Time", "With Constructed Bridges", "To Health Post"], ],
  travel_time_constructed_sites_major_hospitals_optimal: [["Travel Time", "With Constructed Bridges", "To Hospital"], ],
  travel_time_constructed_sites_primary_schools_fixed: [["Travel Time", "With Constructed Bridges", "To Primary School"], ],
  travel_time_constructed_sites_secondary_schools_fixed: [["Travel Time", "With Constructed Bridges", "To Secondary School"], ],
  travel_time_constructed_sites_semi_dense_urban_optimal: [["Travel Time", "With Constructed Bridges", "To Market"], ],
  travel_time_health_centers_optimal: [["Travel Time", "With Bridges", "To Health Center"], ],
  travel_time_health_posts_optimal: [["Travel Time", "With Bridges", "To Health Post"], ],
  travel_time_major_hospitals_optimal: [["Travel Time", "With Bridges", "To Hospital"], ],
  travel_time_no_sites_all_education_facilities_fixed: [["Travel Time", "With No Bridges", "To School"], ],
  travel_time_no_sites_all_health_facilities_optimal: [["Travel Time", "With No Bridges", "To Healthcare"], ],
  travel_time_no_sites_health_centers_optimal: [["Travel Time", "With No Bridges", "To Health Center"], ],
  travel_time_no_sites_health_posts_optimal: [["Travel Time", "With No Bridges", "To Health Post"], ],
  travel_time_no_sites_major_hospitals_optimal: [["Travel Time", "With No Bridges", "To Hospital"], ],
  travel_time_no_sites_primary_schools_fixed: [["Travel Time", "With No Bridges", " To Primary School"], ],
  travel_time_no_sites_secondary_schools_fixed: [["Travel Time", "With No Bridges", " To Secondary School"], ],
  travel_time_no_sites_semi_dense_urban_optimal: [["Travel Time", "With No Bridges", "To Market"], ],
  travel_time_primary_schools_fixed: [["Travel Time", "With All Bridges", "To Primary School"], ],
  travel_time_secondary_schools_fixed: [["Travel Time", "With All Bridges", "To Secondary School"], ],
  travel_time_semi_dense_urban_optimal: [["Travel Time", "With All Bridges", "To Market"], ],
};
